
/*
  QUESTION section
  QUESTION section
  QUESTION section
*/

//get questions action constants
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR';


//single DOCTORS ANSWERS actions constants
export const GET_SINGLE_DOCTOR_ANSWERS = 'GET_SINGLE_DOCTOR_ANSWERS';
export const GET_SINGLE_DOCTOR_ANSWERS_ERROR = 'GET_SINGLE_DOCTOR_ANSWERS_ERROR';
export const GET_SINGLE_DOCTOR_ANSWERS_SUCCESS = 'GET_SINGLE_DOCTOR_ANSWERS_SUCCESS';

//single DOCTORS ANSWERS actions constants
export const GET_SINGLE_QUESTION_ALL_IMG = 'GET_SINGLE_QUESTION_ALL_IMG';
export const GET_SINGLE_QUESTION_ALL_IMG_ERROR = 'GET_SINGLE_QUESTION_ALL_IMG_ERROR';
export const GET_SINGLE_QUESTION_ALL_IMG_SUCCESS = 'GET_SINGLE_QUESTION_ALL_IMG_SUCCESS';


//single DOCTORS ANSWERS actions constants
export const GET_SINGLE_QUESTION = 'GET_SINGLE_QUESTION';
export const GET_SINGLE_QUESTION_ERROR = 'GET_SINGLE_QUESTION_ERROR';
export const GET_SINGLE_QUESTION_SUCCESS = 'GET_SINGLE_QUESTION_SUCCESS';

//create single answer DOCTORS ANSWERS actions constants
export const CREATE_SINGLE_QUESTION_ANSWER = 'CREATE_SINGLE_QUESTION_ANSWER';
export const CREATE_SINGLE_QUESTION_ANSWER_ERROR = 'CREATE_SINGLE_QUESTION_ANSWER_ERROR';
export const CREATE_SINGLE_QUESTION_ANSWER_SUCCESS = 'CREATE_SINGLE_QUESTION_ANSWER_SUCCESS';


export const CLEAR_NEW_ANSWER_STATE = 'CLEAR_NEW_ANSWER_STATE';

/*
  SERVICE section
  SERVICE section
  SERVICE section
*/


//service action type
export const GET_SERVICE_ORDER = 'GET_SERVICE_ORDER';
export const GET_SERVICE_ORDER_SUCCESS = 'GET_SERVICE_ORDER_SUCCESS';
export const GET_SERVICE_ORDER_ERROR = 'GET_SERVICE_ORDER_ERROR';

//service action type
export const ACCEPT_SERVICE_ORDER = 'ACCEPT_SERVICE_ORDER';
export const ACCEPT_SERVICE_ORDER_SUCCESS = 'ACCEPT_SERVICE_ORDER_SUCCESS';
export const ACCEPT_SERVICE_ORDER_ERROR = 'ACCEPT_SERVICE_ORDER_ERROR';

export const CLEAR_ORDER_STATE = 'CLEAR_ORDER_STATE';